### ISSUE TITLE
Multiple questions about things from README.md

### ISSUE THREAD

**Issue by Curt-Park** [tudelft/SGBA_code_SR_2019#3]
Hi! [BitCraze's blog post](https://www.bitcraze.io/2019/10/enabling-swarm-exploration/) brought me here.

I am having difficulties to follow some progress written in README.

In [Real-World Testing](https://github.com/tudelft/SGBA_code_SR_2019#real-world-testing), 
1. it states I should use 'systemtest_gradientbug' branch on Crazyflie2-nrf-firmware (https://github.com/tudelft/crazyflie2-nrf-firmware), but I cannot find the branch on the repo. 
2. where is the following bash scripts?
- gradient_bug/bashscripts/flash_all_crazyflies.sh
- gradient_bug/bashscripts/start_swarm_exploration_experiment.sh
- land_all.sh

It will be so appreciated If you do me a favor.
Thanks!

**Comment by knmcguire** [comment]
Hi! thank you for your question. 

So the blogpost was actually introducing the updated code in the new 'app layer' of the crazyflie firmware, which is here: https://github.com/tudelft/SGBA_CF2_App_layer. I would advise to use that instead actually since that is based on the latest firmware and does not need an custom NRF firmware.

About your questions:

- That is a mistake in the readme. It is actually 'ptx_mode_try_out' : https://github.com/tudelft/crazyflie2-nrf-firmware/tree/ptx_mode_own_tryout
- Ah you are right, they are missing! Strange since they are part of the repo. I will add them tonight. The applayer repo has some bashscripts as well though.

**Comment by knmcguire** [comment]
Hi, the bashscripts are now added so I'm closing the issue now. Still advice you to look at the new version of the code though, so let me know if you have any more questions.

**Comment by Curt-Park** [comment]
@knmcguire Thanks for your fast response!
I tried to run with the newly merged commit, but there are still a few obstacles.

1. the SDK download links don't work in `crazyflie2-nrf-firmware`
2. python scripts are missing which are used by bash files.

I made a pull-request to resolve the first issue so that it works:
https://github.com/tudelft/crazyflie2-nrf-firmware/pull/1 (Please review this!)
However, I think I should ask the proper solution again about the second issue. 
(I made it as another issue: https://github.com/tudelft/SGBA_code_SR_2019/issues/4 )
